[package]
name = "dk"
version = "0.1.0"
authors = ["Joe Becher <me@drazisil.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
volatile = "0.4.5"
spin = "0.9.4"
bootloader = "0.10.13"
