[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]


[build]
target = "src/x86_64-unknown-none.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"